import type { Metadata } from "next";
import { Bellefair, Barlow } from "next/font/google";
import "@/styles/globals.scss";

const bellefair = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bellefair",
});
const barlow = Barlow({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Duccini Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bellefair.variable} ${barlow.variable}`}>
      <body>{children}</body>
    </html>
  );
}
